version: '3.9'
services:  
  api_gatway:
    image: devopsfaith/krakend:2.0.0
    container_name: api_gatway_ct
    volumes:
      - ./krakend:/etc/krakend/
    depends_on:
      - auction_service
      - order_record_service
    ports:
      - "8080:8081"
  auction_service:
    build:
      context: ./../inventoryservice
    container_name: inventory_service_ct
    ports:
      - "5000:5000"
  